---
# Offline Mode
offline_install: false

# Firewall
manage_firewall: true
iscsi_firewall_zone: public

# HA cluster specific varibles
clustered: false 
overwrite_lvm_conf: true

pcs_cluster_name: iscsicluster
pcs_user: hacluster

#Only enable if Ceph repos aren't installed on the iscsi gateway nodes.
repo_install: false
ceph_stable_release: 18.2.2
