---
- name: create scst.conf to load kernel modules at boot
  copy:
    src: scst.conf
    dest: /etc/modules-load.d/scst.conf
    owner: root
    group: root
    mode: '0644'

- name: load scst kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - iscsi-scst
    - scst
    - scst_vdisk

- name: Create iscsi-scst systemd file
  copy:
    src: iscsi-scst.service
    dest: /etc/systemd/system/iscsi-scst.service
    owner: "root"
    group: "root"
    mode: 0755

- name: Create empty scst.conf file
  copy:
    content: ""
    dest: /etc/scst.conf
    force: false # Dont overwrite if already in place
    group: root
    owner: root
    mode: 0644

- name: Start iscsi-scst service
  systemd:
    name: iscsi-scst
    state: started
    enabled: yes
    masked: no 

