- name: validate firewall options
  block:
    - name: make sure firewalld is installed
      shell: command -v firewall-cmd
      args:
        executable: /bin/bash
      failed_when: false
      register: firewall_package
    
    - name: fail if manage_firewall is true, but firewalld is not present
      fail:
        msg: "Firewalld is not installed. Either install firewalld or set manage_firewall to false"
      when: firewall_package.rc != 0

    - name: get firewalld state
      command: /usr/bin/firewall-cmd --state
      failed_when: false
      register: firewall_state

    - name: fail if manage_firewall is true, but firewalld is not running
      fail:
        msg: "firewalld is not running, cant manage firewall. Either start firewalld or set manage_firewall to false"
      when: firewall_state.rc != 0