---
- include_tasks: repository.yml
  when:
    - not offline_install

- include_tasks: rhel.yml
  when:
    - ansible_facts['os_family'] == 'RedHat'

- include_tasks: ubuntu.yml
  when: 
    - ansible_facts['distribution'] == 'Ubuntu'
