- name: setup 45drives repository
  block:
  - name: Configure 45Drives repository | Get repo setup script
    get_url:
      url: https://repo.45drives.com/setup
      dest: /tmp/setup

  - name: Configure 45Drives repository | Run repo setup script
    shell: bash /tmp/setup

  - name: Configure 45Drives repository | Remove repo setup script
    file:
      path: /tmp/setup
      state: absent

- name: setup ceph repository on rhel family OS
  when: 
    - ansible_facts['os_family'] == 'RedHat'
    - clustered | bool
  block:
    - name: install yum plugin priorities
      package:
        name: yum-plugin-priorities
      register: result
      until: result is succeeded
      when: ansible_facts['distribution_major_version'] | int == 7

    - name: Check if ceph-stable.repo exists
      stat:
        path: /etc/yum.repos.d/ceph-stable.repo
      register: ceph_stable_check

    - name: Add Ceph repository (Rocky Linux)
      copy:
        content: |
          [Ceph-Stable]
          name=Ceph packages
          baseurl={{ ceph_rocky_repo }}x86_64/
          enabled=1
          gpgcheck=1
          type=rpm-md
          gpgkey=https://download.ceph.com/keys/release.asc

          [Ceph-Noarch]
          name=Ceph noarch packages
          baseurl={{ ceph_rocky_repo }}noarch/
          enabled=1
          gpgcheck=1
          type=rpm-md
          gpgkey=https://download.ceph.com/keys/release.asc
        dest: /etc/yum.repos.d/ceph-stable.repo
      when: not ceph_stable_check.stat.exists

- name: setup ceph repository on debian family OS
  when: 
    - ansible_facts['os_family'] == 'Debian'
    - clustered | bool
  block:
    - name: install dependencies for apt modules
      package:
        name: ['apt-transport-https', 'ca-certificates', 'gnupg', 'software-properties-common']
        update_cache: yes
      register: result
      until: result is succeeded

    - name: configure debian ceph community repository stable key
      apt_key:
        url: "{{ ceph_stable_key }}"
        state: present
      register: result
      until: result is succeeded

    - name: configure debian ceph stable community repository
      apt_repository:
        repo: "deb https://download.ceph.com/debian-{{ ceph_stable_release }}/ {{ ansible_facts['distribution_release'] }} main"
        state: present
        update_cache: yes

    - name: update apt cache if cache_valid_time has expired
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: result
      until: result is succeeded

- name: Enable HighAvailablity repo in rhel and clustered environments
  shell: dnf config-manager --set-enabled ha
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '8'
    - clustered | bool

- name: Enable HighAvailablity repo in rhel and clustered environments (Rocky9)
  shell: dnf config-manager --set-enabled highavailability
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '9'
    - clustered | bool
