---
- name: remove conflicting iscsi packages
  package:
    name: "{{ item }}"
    state: absent
  register: result
  until: result is succeeded
  with_items:
    - targetcli

- name: Install DKMS
  package:
    name: "dkms"
    state: present
  register: result
  until: result is succeeded 

- name: Install iSCSI packages
  package:
    name: "{{ item }}"
    state: present
  register: result
  until: result is succeeded
  with_items:
    - scst-dkms 
    - scst-dkms-userspace
    - scstadmin 

- name: Install High Availability Packages
  package:
    name: "{{ item }}"
    state: present
  register: result
  until: result is succeeded
  when: clustered | bool
  with_items:
    - pcs
    - pacemaker
    - corosync
    - ceph-resource-agents
